const actionTypes = {
    GET_HOME: 'GET_HOME',  
    SET_SHOW_PLAYLIST_SIDEBAR: 'SHOW_PLAYLIST_SIDEBAR',
    
    //music
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_IS_PLAYING: 'SET_IS_PLAYING',
    SET_PLAYLIST_SONGS: 'SET_PLAYLIST_SONGS',
    ADD_RECENT_SONG: 'ADD_RECENT_SONG',
    SET_CUR_SONG_INDEX: 'SET_CUR_SONG_INDEX'
}

export default actionTypes